CC = gcc
CFLAGS = -Wall
NAME = advanced_do_op
INCLUDE_DIR = -I../../libs/libft/includes
LIB_DIR = -L../../libs/libft/
LIB_NAME = -lft

all:
	$(CC) $(CFLAGS) ./*.c -o $(NAME) $(INCLUDE_DIR) $(LIB_DIR) $(LIB_NAME)

clean: 
	rm $(NAME)