CC = gcc
FLAGS = -Wall -g3
NAME = ft_sort_wordtab_advanced
INCLUDE_DIR = -I../../libs/libft/includes/
LIB_DIR = -L../../libs/libft/
LIB_NAME = -lft

all:
	$(CC) $(FLAGS) *.c $(INCLUDE_DIR) $(LIB_DIR) $(LIB_NAME) -o $(NAME)

clean:
	rm $(NAME)
