void ft_putchar(char c);
void ft_putstr(char* str);
char* ft_strcat(char *dest, char *src);
int ft_strncmp(char* s1, char* s2, unsigned int n);
char* ft_strcpy(char *dest, char *src);
unsigned int ft_strlcat(char *dest, char *src, unsigned int size);
int ft_strlen(char *str);
char* ft_strncat(char *dest, char *src, int n);
char* ft_strncpy(char* dest, char* src, unsigned int n);
void ft_swap(int *a, int *b);
