CC = gcc
FLAGS = -g3 -Wall -Wextra -Werror

SRC_FILES = display_file.c

OUT_FILE = display_file

all:
	$(CC) $(FLAGS) $(SRC_FILES) -o $(OUT_FILE)

clean:
	rm -f $(OUT_FILE)

fclean: clean

re: fclean all