gcc ft_putchar.c -o ft_putchar.o
gcc ft_putstr.c -o ft_putstr.o
gcc ft_strcat.c -o strcat.o
gcc ft_strcmp.c -o ft_strcmp.o
gcc ft_strcpy.c -o ft_strcpy.o
gcc ft_strlcat.c -o ft_strlcat.o
gcc ft_strlen.c -o ft_strlen.o
gcc ft_strncat.c -o ft_strncat.o
gcc ft_strncpy.c -o ft_strncpy.o
gcc ft_swap.c -o ft_swap.o
gcc testlib.c -o ft_testlib.o